### ISSUE TITLE
Integración de micro clientes en ambiente de pruebas 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#126]
Se requiere realizar la Integración de micro clientes en ambiente de pruebas 

**Sub Tareas**

- [x] Revisar flujo de despliegue para la Integración de micro clientes en ambiente de pruebas 
- [x] Realizar ajustes necesarios para el correcto funcionamiento de la Integración de micro clientes en ambiente de pruebas 
- [x] realizar despliegue en el entorno de pruebas 

**Criterios de aceptación**

- [x] Analizar y ajustar para Integración de micro clientes en ambiente de pruebas 
- [x] Realizar el despliegue en pruebas 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by NeFaWaltPint** [comment]
### Ajustes relevantes para microfrontends
`.drone.yml`
```yml
 # procurar correr esta versión (aplica local también), se sabe que funciona para los clientes en angular 16~ e inferiores
- name: nodejs_release
  image: node:16.20.2
  commands:
  - node --version
  - npm i
  - npm run build:test
  when:
    branch:
    - release/*
    event:
    - push
```

`package.json`
```json
"scripts": {
    // define comandos para despliegue
    "build:prod": "ng build --progress --configuration=production",
    "build:test": "ng build --progress --configuration=development"
...
"devDependencies": {
    // procurar usar esta versión para que pueda correr distintos microclientes local sin problema
    "@angular/cli": "^16.2.12",
```

`angular.json`
```json
"options": {
   // que la carpeta de compilación quede solo así
   "outputPath": "dist",
....
"configurations": {
  "production": {
    // ajustes para despliegue de esta manera
    "optimization":true,
    "outputHashing": "none",
    "sourceMap": false,
    "namedChunks": false,
    "aot": true,
    "extractLicenses": true,
    "buildOptimizer": true,
    "fileReplacements": [
      {
        "replace": "src/environments/environment.ts",
        "with": "src/environments/environment.production.ts"
      }
    ],
    "deployUrl": "https://sgagestionperiodo.portaloas.udistrital.edu.co/"
  },
```
Para más detalle revisar este microcliente: [sga_cliente_gestion_periodo_mf](https://github.com/udistrital/sga_cliente_gestion_periodo_mf)
